language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-26 ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-26
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-26
    - extra-android-support

before_script:
- chmod +x ./gradlew
script:
- ./gradlew build
- ./gradlew build jacocoTestReport assembleAndroidTest


after_success:
- bash <(curl -s https://codecov.io/bash)